version: "3"

services:
  app:
    build: .
    image: magnetico/nodejs-server:local
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: "development"
      PORT: 3000
      REDIS_URL: "redis://redis:6379/0"
      JWT_SECRET: "958f24c13fac8d23b9b7a09f22088bb6b01743143e2ffad870a27da29121fd4a"
      MONGO_URL: "mongodb://root:iamroot@mongo:27017/db?authSource=admin"
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: iamroot
      MONGO_INITDB_DATABASE: db
